wandb_version: 1

lamb_0:
  desc: null
  value: 42.11628514546421
lamb_end:
  desc: null
  value: 28.571967351534536
std_0:
  desc: null
  value: 30.13018550968218
std_end:
  desc: null
  value: 23.99793474777358
tau:
  desc: null
  value: 0.04284146369850991
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700815245.226453
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.18
      5: 0.15.4
      8:
      - 5
