wandb_version: 1

lamb_0:
  desc: null
  value: 69.34077371074336
lamb_end:
  desc: null
  value: 3.750782519441869
std_0:
  desc: null
  value: 91.62645348595316
std_end:
  desc: null
  value: 6.151404090060042
tau:
  desc: null
  value: 0.003211586010525549
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700815475.930043
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.18
      5: 0.15.4
      8:
      - 5
