wandb_version: 1

lamb:
  desc: null
  value: 0.05
std:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.15.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705914130.560583
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.6
      5: 0.15.4
      8:
      - 5
