wandb_version: 1

lamb_0:
  desc: null
  value: 42.59046627484079
lamb_end:
  desc: null
  value: 4.5050532641708285
std_0:
  desc: null
  value: 83.91819030049196
std_end:
  desc: null
  value: 5.174404776568868
tau:
  desc: null
  value: 0.0006318345524459208
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700816273.053159
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.18
      5: 0.15.4
      8:
      - 5
