wandb_version: 1

lamb_0:
  desc: null
  value: 36.01770609232338
lamb_end:
  desc: null
  value: 0.7481117047430683
std_0:
  desc: null
  value: 86.12230397095743
std_end:
  desc: null
  value: 4.828788203793209
tau:
  desc: null
  value: 0.0008234431966742244
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700815634.051206
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.18
      5: 0.15.4
      8:
      - 5
