wandb_version: 1

lamb_0:
  desc: null
  value: 53.38855522660592
lamb_end:
  desc: null
  value: 3.255375921361006
std_0:
  desc: null
  value: 97.83963189122566
std_end:
  desc: null
  value: 1.2402298439662471
tau:
  desc: null
  value: 0.0040444731826830655
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700815710.565917
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.18
      5: 0.15.4
      8:
      - 5
