wandb_version: 1

lamb_end:
  desc: null
  value: 0.7
maxitr:
  desc: null
  value: 500
std_end:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.15.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705932987.890028
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 23
      - 37
      4: 3.9.6
      5: 0.15.4
      8:
      - 5
