wandb_version: 1

lamb_0:
  desc: null
  value: 149.85330814075255
lamb_end:
  desc: null
  value: 4.273437197807789
std_0:
  desc: null
  value: 32.383487294731
std_end:
  desc: null
  value: 16.166896938698656
tau:
  desc: null
  value: 0.011200787748653048
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700815208.381813
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.18
      5: 0.15.4
      8:
      - 5
