wandb_version: 1

lamb_0:
  desc: null
  value: 49.76755474263983
lamb_end:
  desc: null
  value: 4.705880774180903
std_0:
  desc: null
  value: 99.84075509167522
std_end:
  desc: null
  value: 8.868564538206863
tau:
  desc: null
  value: 0.0005650253937476585
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700816861.411708
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.18
      5: 0.15.4
      8:
      - 5
