wandb_version: 1

lamb_0:
  desc: null
  value: 49.90141575002404
lamb_end:
  desc: null
  value: 4.449484429876232
std_0:
  desc: null
  value: 91.11582828830208
std_end:
  desc: null
  value: 9.124782736323432
tau:
  desc: null
  value: 0.0006081104493981326
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700816939.883092
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.18
      5: 0.15.4
      8:
      - 5
