wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700754092.158815
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 23
      4: 3.9.18
      5: 0.15.4
      8:
      - 5
    visualize:
      psnr_plot:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/scatter/v0
          fieldSettings:
            x: k
            y: psnr
          stringSettings:
            title: psnr vs. k
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: psnr_plot_table
                fields: []
      n_it_plot:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/scatter/v0
          fieldSettings:
            x: k
            y: n_it
          stringSettings:
            title: n_it vs. k
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: n_it_plot_table
                fields: []
